name: GLuaFixer

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/entities/gmod_wire_expression2/**'
  pull_request:
    paths:
    - 'lua/**'
    - '!lua/entities/gmod_wire_expression2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download GLuaFixer 1.17.2
      run: curl -o glualint.zip -L https://github.com/FPtje/GLuaFixer/releases/download/1.17.2/glualint-1.17.2-linux.zip
    - name: Extract glualint.zip
      run: unzip glualint.zip
    - name: Remove blacklisted folders
      run: rm -r lua/entities/gmod_wire_expression2/
    - name: Initiate linting
      run: ./glualint lua
